version: '3.8'
services:
  backend:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.cu5n6zivfyad.ap-northeast-2.rds.amazonaws.com:3306/hotdeal_verse
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: "!sk3693690"
    ports:
      - 8080:8080