server:
  port: 8080



spring:

  ##### mysql ######
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotdeal_verse?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    # show-sql: true
    hibernate:
      ddl-auto: update
    # properties:
    #  hibernate:
    #    format_sql: true

  ##### OAuth2 #####
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ebc80626860a242dc871399ffb7e553d
            redirect-uri: "http://localhost:8080/oauth2/callback/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email #동의 항목
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  ##### Swagger3 #####
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  accessToken:
    secret: sssssecret
    expiredMsc: 1000000000
  refreshToken:
    expiredMsc: 1209600000

frontend:
  redirectUrl: http://localhost:3000/oauth2/redirect