# properties:
server:
  port: 9787

spring:

  ##### mysql ######
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: "WGh0tuca42zgagzfMGYH"
    url: jdbc:mysql://hotdealverse-dev.cloksitufzqo.ap-northeast-2.rds.amazonaws.com:3306/hotdeal_verse?characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    # show-sql: true
    hibernate:
      ddl-auto: update
    # properties:
    # hibernate:
    #  format_sql: true


  ##### OAuth2 #####
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b7476de0da29fde52ab0fb353df9961e
            redirect-uri: "https://api.hotdealverse.shop/oauth2/callback/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email #동의 항목
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



  ##### Swagger3 #####
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    #### rabbitmq ####
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    exchange: exchange
    list:
      - queue: message
        key: key1
      - queue: email
        key: key2


jwt:
  accessToken:
    secret: gktelfqjtmfosejazlrkqtdla
    expiredMsc: 3600000
  refreshToken:
    expiredMsc: 1209600000

frontend:
  redirectUrl: http://localhost:5173/oauth2/redirect
  email:
    redirectUrl: http://localhost:5173/redirect/email
