server:
  port: 8761

spring:

  application:
    name: discovery

  security:
    user:
      name: user
      password: 1234


eureka:

  client:
    register-with-eureka: false # eureka? registry? ???? ??
    fetch-registry: false # registry? ?? ??? ???? ??
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname:localhost}:8761/eureka

  server:
    peer-node-read-timeout-ms: 10000